name: tvcubana
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  parse_server_sdk: ^1.0.26
  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  flutter_launcher_icons: ^0.7.5
  chips_choice: ^1.2.0
  webview_flutter: ^0.3.22+1
  flutter_local_notifications: ^1.4.4+2
  lite_rolling_switch: ^0.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/canal_caribe.jpg
    - assets/images/artemisa_tv.jpg
    - assets/images/multivision-icon.png
    - assets/images/cubavision-icon.png
    - assets/images/cubavision_plus.png
    - assets/images/canalHabana-icon.png
    - assets/images/cubavision_internacional.png
    - assets/images/clave.jpg
    - assets/images/educativo-icon.png
    - assets/images/educativo2-icon.png
    - assets/images/telerebelde-icon.jpg
    - assets/images/telerebeldePlus-icon.png
    - assets/images/tele_mayabeque.jpg
    - assets/images/yayabo_tv.jpg
    - assets/images/telepinar-icon.jpg
    - assets/images/tele_cubanacan.jpg
    - assets/images/tele_cristal.jpg
    - assets/images/mitv.jpg
    - assets/images/noresult.jpg
    - assets/images/icon.png
    - assets/images/tvavilena-icon.png
    - assets/images/cnctv-icon.jpeg
    - assets/images/islavision-icon.png
    - assets/images/perlavision-icon.png
    - assets/images/rusiaToday-icon.png
    - assets/images/solvision-icon.jpeg
    - assets/images/tunasvision-icon.png
    - assets/images/tvSantiago-icon.jpg
    - assets/images/tvyumuri-icon.png
    - assets/images/tvcamaguey-icon.png
    - assets/images/icon_noresults.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/icon.png"
